import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";

const fontBarlow = Barlow_Condensed({
  weight: ["400", "700"],
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fazfood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MainLayout>
        <body className={`${fontBarlow.variable}  antialiased`}>
          {children}
        </body>
      </MainLayout>
    </html>
  );
}
